import type { Dish } from './catalog.types';

// Fixtures fictives reprises du prototype Flutter, aucun établissement vérifié.
export const demoDishes: readonly Dish[] = [
  {
    servings: 1,
    available: true,
    open: true,
    daily: false,
    rating: 4.8,
    reviewCount: 46,
    likes: 248,
    id: 'big-burger',
    name: 'Le Big Burger',
    category: 'Burger',
    price: 18000,
    restaurant: 'Maison Boma',
    area: 'Gombe',
    image: 'burger',
    description:
      'Un steak généreux, du cheddar fondant, des oignons croquants et notre sauce maison. Le genre de burger auquel on repense.',
    priceCdf: '18000.00',
    currency: 'CDF',
    restaurantId: 'maison-boma',
  },
  {
    servings: 1,
    available: true,
    open: true,
    daily: true,
    rating: 4.9,
    reviewCount: 63,
    likes: 186,
    id: 'poulet-braise',
    name: 'Poulet braisé',
    category: 'Poulet',
    price: 12000,
    restaurant: 'Chez Mama Rose',
    area: 'Bandalungwa',
    image: 'chicken',
    description:
      'Poulet mariné aux épices, grillé doucement à la braise. Servi avec une portion de bananes plantains et une sauce pimentée à part.',
    priceCdf: '12000.00',
    currency: 'CDF',
    restaurantId: 'chez-mama-rose',
  },
  {
    servings: 2,
    available: true,
    open: true,
    daily: false,
    rating: 4.6,
    reviewCount: 28,
    likes: 172,
    id: 'pizza-familiale',
    name: 'Pizza à partager',
    category: 'Pizza',
    price: 25000,
    restaurant: 'Maison Boma',
    area: 'Gombe',
    image: 'pizza',
    description:
      'Une pâte croustillante, une sauce tomate parfumée et une mozzarella généreuse. Une pizza à partager à deux.',
    priceCdf: '25000.00',
    currency: 'CDF',
    restaurantId: 'maison-boma',
  },
  {
    servings: 1,
    available: true,
    open: true,
    daily: true,
    rating: 4.5,
    reviewCount: 19,
    likes: 94,
    id: 'bol-du-jour',
    name: 'Le bol du marché',
    category: 'Congolais',
    price: 9500,
    restaurant: 'Le Jardin de Kin',
    area: 'Limete',
    image: 'bowl',
    description:
      'Un bol coloré de légumes de saison, riz et sauce maison. Une pause légère et généreuse.',
    priceCdf: '9500.00',
    currency: 'CDF',
    restaurantId: 'le-jardin-de-kin',
  },
  {
    servings: 1,
    available: true,
    open: true,
    daily: false,
    rating: 4.7,
    reviewCount: 37,
    likes: 137,
    id: 'grillades-maison',
    name: 'Les grillades maison',
    category: 'Grillades',
    price: 22000,
    restaurant: 'Le Jardin de Kin',
    area: 'Limete',
    image: 'grill',
    description:
      'Une belle assiette de grillades et légumes rôtis. Servie avec des pommes de terre et une sauce maison.',
    priceCdf: '22000.00',
    currency: 'CDF',
    restaurantId: 'le-jardin-de-kin',
  },
  {
    servings: 1,
    available: true,
    open: true,
    daily: false,
    rating: 4.6,
    reviewCount: 24,
    likes: 89,
    id: 'burger-classique',
    name: 'Le Classique',
    category: 'Burger',
    price: 14000,
    restaurant: 'Maison Boma',
    area: 'Gombe',
    image: 'burger',
    description:
      'Steak, salade, tomate et fromage dans un pain toasté. Frites incluses, boisson non incluse.',
    priceCdf: '14000.00',
    currency: 'CDF',
    restaurantId: 'maison-boma',
  },
  {
    servings: 1,
    available: true,
    open: false,
    daily: false,
    rating: 4.8,
    reviewCount: 21,
    likes: 76,
    id: 'douceur-chocolat',
    name: 'Douceur chocolat',
    category: 'Desserts',
    price: 6500,
    restaurant: 'Café du Fleuve',
    area: 'Ngaliema',
    image: 'dessert',
    description:
      'Une part de gâteau au chocolat et sa ganache fondante. Pour terminer sur une jolie note.',
    priceCdf: '6500.00',
    currency: 'CDF',
    restaurantId: 'cafe-du-fleuve',
  },
  {
    servings: 1,
    available: false,
    open: false,
    daily: false,
    rating: 4.4,
    reviewCount: 16,
    likes: 62,
    id: 'poulet-signature',
    name: 'Poulet signature',
    category: 'Poulet',
    price: 16000,
    restaurant: 'Café du Fleuve',
    area: 'Ngaliema',
    image: 'chicken',
    description:
      'Poulet rôti, légumes de saison et jus parfumé. Une assiette généreuse pour une personne.',
    priceCdf: '16000.00',
    currency: 'CDF',
    restaurantId: 'cafe-du-fleuve',
  },
];
